In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris

iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

In [5]:
from sklearn.model_selection import cross_val_score

In [6]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

/Users/richa/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [7]:
np.average(l_scores)

0.9733333333333334

In [8]:
SVC_scores = cross_val_score(SVC(), iris.data, iris.target)
SVC_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [9]:
np.average(SVC_scores)

0.9666666666666666

In [10]:
r_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [11]:
np.average(r_scores)

0.9666666666666668