In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv('/Users/richa/Desktop/python/jupyter_notebooks/datasource/homeprices_multival.csv')
df
# We can check in the below dataframe, price of the home depends on three variable area, bedrooms and age
# so linear equation will look like y=m1*x1 + m2*x2 + m3*x3 + b 
# here m1, m2, m3 are the co-efficient and b is the constant
# We have to replace NaN value with some other value in the bedrooms column i.e handelling the missing data points

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
# For the missing datapoint median value of the column will be sutible
df.bedrooms.median()
# if medain output in decimal form but bedroom column should have roundoff value then import math

4.0

In [4]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [5]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

# Data cleaning is done, we should alway clean the data before applying any regression model

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg=linear_model.LinearRegression()
# 'area','bedrooms','age' are the independent variables and price is the dependent variable, 
# for calculating price we need 'area','bedrooms','age' 
reg.fit(df[['area','bedrooms','age']],df.price)
# Now our function is ready to predict

LinearRegression()

In [7]:
reg.coef_
# here m1 = 112.06244194 , m2 = 23388.88007794, m3=-3231.71790863

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_
# b=221323.00186540408


221323.00186540408

In [9]:
reg.predict([[3000,5,40]])

/Users/richa/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([545186.01173619])

In [10]:
# y = m1*x1 + m2*x2 _m3*x3
112.06244194*3000 + 23388.88007794*5 + -3231.71790863*40 + 221323.00186540408


545186.0117299041

In [11]:
reg.predict([[2500,4,5]])

/Users/richa/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])